# Generated by Django 5.2.4 on 2025-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dailyreport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
