# Generated by Django 5.2.4 on 2025-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_zone_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
